### ISSUE TITLE
DAMMviz() key Symbol("Moles CO₂") not found

### ISSUE THREAD

**Issue by BernhardAhrens** [CUPofTEAproject/DAMMmodel.jl#11]
Hi Alexis,

when I run DAMMviz() using DAMMmodel v0.1.8 and UnitfulMoles v0.1.1, I get the following error message:
KeyError: key Symbol("Moles CO₂") not found.

Btw, DAMMmodel v0.1.7 works fine for me. Based on v0.1.7, I have added a Q10 for KmSx in a branch on my GitHub https://github.com/BernhardAhrens/DAMMmodel.jl/tree/Q10_of_KmSx.

Also some other changes in there, like producing NaN when porosity is smaller than water content and a reference temperature for the Arrhenius function. This makes the Arrhenius function more Q10 like and may alleviate some equifinality issues when estimating alpha_Sx and Ea at the same time.

**Comment by AlexisRenchon** [comment]
Hi @BernhardAhrens, 
You're right, I am not sure why this is happening... we had to fix UnitfulMoles @compound yesterday because of a Julia Registry problem. It is fixed now, but it seems I need to do things differently... In the meantime, DAMMmodel v0.1.8 will work if you do 
```
using Unitful, UnitfulMoles
@compound CO₂
```
That's the missing key Symbol("Moles CO₂"). 
It is supposed to [be called in DAMMmodel.jl](https://github.com/CUPofTEAproject/DAMMmodel.jl/blob/master/src/DAMMmodel.jl), but it doesn't work for some reason. I will try to fix it asap

Edit: Note that you'll have to slightly modify DAMMfit.jl with your added parameter Q10_of_KmSx

Edit2: you can also add a slider in DAMMviz() to have interactivity with your parameter
I am registering a v0.1.9 which should fix the error, it should be up in 15 to 30 min

**Comment by AlexisRenchon** [comment]
@BernhardAhrens  Well my 0.1.9 fix did not work... I'll continue trying to fix this today

Edit: I've [opened an issue](https://github.com/rafaqz/UnitfulMoles.jl/issues/19) on UnitfulMoles.jl

**Comment by AlexisRenchon** [comment]
Hi @BernhardAhrens , this has been fixed in v0.1.10, let me know if it works for you and I will close the issue!

**Comment by BernhardAhrens** [comment]
Thanks, @AlexisRenchon for fixing this so quickly! Also, the additional lines and helper points in DAMMviz look great!!
